services:
  emenu-api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - emenu-api
    restart: unless-stopped